---

- name: Generate list of .tf and .cfg files to keep
  ansible.builtin.set_fact:
    files_to_keep: []

- name: Add fixed resources files to keep list
  ansible.builtin.set_fact:
    files_to_keep: "{{ files_to_keep + [ tf_config_dir + '/' + item + '.tf' ] }}"
  with_items:
    - 'provider'
    - 'networks'
    - 'pools'
    - 'volumes'
    - 'cloud_init'
    - 'coreos_ignition'

- name: Add dynamic cloud_init.cfg files to keep list
  ansible.builtin.set_fact:
    files_to_keep: "{{ files_to_keep + [ tf_config_dir + '/cloud_init_' + item.0.name + '.' + item.1 + '.cfg' ] }}"
  when: item.0[item.1] is defined
  with_nested:
    - "{{ tf_libvirt_cloud_inits }}"
    - ["user_data", "network_config"]

- name: debug
  debug: 
    msg: "{{ files_to_keep }}"

- name: Add dynamic .vms.tf files to keep list
  ansible.builtin.set_fact:
    files_to_keep: "{{ files_to_keep + [ tf_config_dir + '/' + item + '.vms.tf' ] }}"
  with_items:
    - "{{ tf_libvirt_vms_groups }}"
  when: tf_libvirt_vms_keep_strategy == 'group'

- name: Add .vms.tf files to keep list using glob from directory
  ansible.builtin.set_fact:
    files_to_keep: "{{ files_to_keep + [item] }}"
  with_fileglob:
    - "{{ tf_config_dir + '/' + tf_libvirt_vms_keep_pattern }}"
  when: tf_libvirt_vms_keep_strategy == 'pattern'

- name: Get the stats (including absolute paths) of the remote files
  ansible.builtin.stat:
    path: "{{ item }}"
  loop: "{{ files_to_keep }}"
  register: files_to_keep_stats

- name: Create a list of files to keep with absolute paths
  ansible.builtin.set_fact:
    files_to_keep_full_path: "{{ files_to_keep_full_path | default([]) + [ item.stat.path ] }}"
  loop: "{{ files_to_keep_stats.results }}"

- name: Generate the list of all the .tf and .cfg files
  ansible.builtin.find:
    paths: "{{ tf_config_dir }}"
    patterns: "*.tf,*.cfg"
  register: all_files

- name: Effectively delete files not to keep
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ all_files.files }}"
  when: item.path not in files_to_keep_full_path
