---

- name: Install tf cmd locally
  ansible.builtin.include_tasks: install.yml
  when:
    - tf_binary_install | bool

- name: Fail if tf_config_dir is not an absolute path
  assert:
    that:
      - tf_config_dir[0] == '/'
    fail_msg: tf_config_dir must be an absolute path
    
- name: "Create local configurations directory {{ tf_config_dir }}"
  ansible.builtin.file:
    path: "{{ tf_config_dir }}"
    state: directory
    mode: '0750'

- name: Deploy Azure environment
  ansible.builtin.include_tasks: azure.yml
  when:
    - tf_cloud_provider == 'azure'

- name: Deploy Libvirt environment
  ansible.builtin.include_tasks: libvirt.yml
  when:
    - tf_cloud_provider == 'libvirt'
